name: 'SmartDiff'
author: 'Kamil Rybacki'
description: 'Finds files that have changed since last code SUCCESFUL workflow.'
inputs:
  include:
    description: 'Regex to use to match the files to include.'
    required: true
  token:
    description: 'Github token to use for the API calls.'
    required: true
  exclude:
    description: 'Regex to use to match the files to ignore.'
    required: false
outputs:
  files:
    description: 'List of changed files kept as GH Workflow output for convenience.'
runs:
  using: 'node16'
  main: 'dist/index.js'
