name: 'SmartDiff'
author: 'Kamil Rybacki'
description: 'Finds files that have changed since last code SUCCESSFUL workflow.'
inputs:
  include:
    description: 'Regex to use to match the files to include.'
    required: true
  tag:
    description: 'Tag used to identify the cache to be used. Same as the name of the secret containing the cache.'
    required: true
  cache:
    description: 'Previously stored cache to use for the comparison. Set it to previously created SMART_DIFF_CACHE secret!'
    required: true
  token:
    description: 'Github token to use for the API calls. Set it to previously created SMART_DIFF_TOKEN secret!'
    required: true
  exclude:
    description: 'Regex to use to match the files to ignore.'
    required: false
outputs:
  files:
    description: 'List of changed files kept as GH Workflow output for convenience.'
runs:
  using: 'node16'
  main: 'dist/index.js'
