name: "Action test"

on:
  push:
  workflow_run:
    workflows: ["Unit tests"]
    types:
      - completed

concurrency:
  group: ${{ github.head_ref }}-action-tests
  cancel-in-progress: true

jobs:
  action-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install "lz-string" library via NPM
      run: npm install lz-string
    - name: Pass the cache to GitHub Envs
      run:
        echo "DIFF_CACHE=${{ secrets.DIFF_CACHE }}" >> $GITHUB_ENV
    - name: Manually read the cache from secret
      uses: actions/github-script@v6
      id: cache-after-unit-tests
      with:
        script: |
          import LZString from 'lz-string';

          const cache = process.env.DIFF_CACHE;
          const cacheDecoded = LZString.decompress(cache);
          const cacheParsed = JSON.parse(cacheDecoded);
          return cacheParsed['.*&&'];
        result-encoding: string
    - name: Check if cache was emptied
      run: |
        if [ -z "${{ steps.cache-after-unit-tests.outputs.result }}" ]; then
          echo "Cache was emptied"
          exit 0
        fi
        echo "Cache was not emptied"
        exit 1
