name: "lint"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  lint-source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

