name: "Functionality tests"

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-tests
  cancel-in-progress: true

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --ignore-scripts
    - uses: actions/github-script@v6
      with:
        script: |
          const { data: { id: check_run_id } } = await github.checks.create({
            ...context.repo,
            name: 'Jest tests',
            head_sha: context.sha,
            status: 'in_progress',
            started_at: new Date().toISOString()
          })
          try {
            await exec.exec('npm', ['run', 'test'])
            await github.checks.update({
              ...context.repo,
              check_run_id,
              status: 'completed',
              conclusion: 'success',
              completed_at: new Date().toISOString()
            })
          } catch (error) {
            await github.checks.update({
              ...context.repo,
              check_run_id,
              status: 'completed',
              conclusion: 'failure',
              completed_at: new Date().toISOString()
            })
            throw error
          }

  gray-box-tests:
    runs-on: ubuntu-latest
    needs: jest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --ignore-scripts
    - run: npm run build
    - uses: ./
      with:
        include: '.*\.py' # Regex for Python files to scan
        token: ${{ secrets.SMART_DIFF_TOKEN }}
