name: "tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: npm test

  live-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: npm run build
    - uses: ./
      with:
        command: 'pylint' # Use pylint to lint Python files
        flags: '--disable=missing-docstring' # Disable missing-docstring check
        regex: '.*\.py' # Regex for Python files to scan
