name: "Functionality tests"

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-tests
  cancel-in-progress: true

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --ignore-scripts
    - name: Manually pass Actions envs
      run:
        echo "GITHUB_TOKEN=${{ secrets.SMART_DIFF_TOKEN }}" >> $GITHUB_ENV
        echo "ACTIONS_RUNTIME_URL=${ACTIONS_RUNTIME_URL}" >> $GITHUB_ENV
    - run: npm test

  gray-box-tests:
    runs-on: ubuntu-latest
    needs: jest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --ignore-scripts
    - run: npm run build
    - uses: ./
      with:
        include: '.*\.py' # Regex for Python files to scan
        token: ${{ secrets.SMART_DIFF_TOKEN }}
