name: "Functionality tests"

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-tests
  cancel-in-progress: true

jobs:
  gray-box-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --ignore-scripts
    - run: npm run build
    - name: Generate test filenames list
      run: |
        filenames=""
        for i in {1..10}; do
          filename=$(date +%s)-$i.mock
          filenames+="$filename "
        done
        echo "FILENAMES=$filenames" >> $GITHUB_ENV
    - name: Create Python files
      run: |
        mkdir -p $GITHUB_WORKSPACE/mock
        cd $GITHUB_WORKSPACE/mock
        for filename in $FILENAMES; do
          echo "print('Hello, World!')" > $filename
        done
    - uses: ./
      with:
        include: '.*\.mock'
        cache_secret: ${{ secrets.DIFF_CACHE }}
        token: ${{ secrets.DIFF_CACHE_TOKEN }}
    - name: Compare values saved in secrets.DIFF_CACHE with list of filenames
      env:
        DIFF_CACHE: ${{ secrets.DIFF_CACHE }}
        FILENAMES: ${{ env.FILENAMES }}
      run: |
        CACHED_FILES=$(echo "$DIFF_CACHE" | jq -r '.".*\.mock&&"')
        echo "Files cached in secrets: $CACHED_FILES"
        echo "Filenames generated for tests: $FILENAMES"
        if [ "$CACHED_FILES" != "$FILENAMES" ]; then
          echo "Values saved in secrets.DIFF_CACHE and list of filenames are different!"
          exit 1
        fi
